# Generated by Django 4.0 on 2024-01-19 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.categoryoftask')),
                ('TaskId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.task')),
            ],
            options={
                'verbose_name_plural': 'CategorySets',
            },
        ),
    ]
