# Generated by Django 4.0 on 2024-01-19 04:51

from django.db import migrations


def create_through_relations(apps, schema_editor):
    Task = apps.get_model('TaskManagerApp', 'Task')
    CategorySet = apps.get_model('TaskManagerApp', 'CategorySet')
    for tsk in Task.objects.all():
        for Category in tsk.CategoryOfTaskName.all():
            CategorySet(
                CategoryId=Category,
                TaskId=tsk
            ).save()

class Migration(migrations.Migration):
    # old ->
    dependencies = [
        ('TaskManagerApp', '0002_categoryset'),
    ]
    # <- old
    # new ->
    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
    # <- new
