# Generated by Django 4.0 on 2024-01-19 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0003_auto_20240119_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='CategoryOfTaskName',
        ),
    ]
