# Generated by Django 4.0 on 2023-12-28 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('TaskManagerApp', '0003_rename_persons_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priorityinfo',
            options={'verbose_name_plural': 'PriorityInfo'},
        ),
        migrations.AlterModelOptions(
            name='resultoftask',
            options={'verbose_name_plural': 'ResultOfTask'},
        ),
        migrations.AddField(
            model_name='task',
            name='Author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
