# Generated by Django 4.0 on 2024-01-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0004_remove_task_categoryoftaskname'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='CategoryOfTaskName',
            field=models.ManyToManyField(through='TaskManagerApp.CategorySet', to='TaskManagerApp.CategoryOfTask'),
        ),
    ]
