# Generated by Django 4.0 on 2024-01-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0005_task_categoryoftaskname'),
    ]

    operations = [migrations.RemoveField(
        model_name='task',
        name='CategoryOfTaskName',
        )
    ]
