# Generated by Django 4.0 on 2024-01-20 11:08

from django.db import migrations


class Migration(migrations.Migration):
    
    dependencies = [
        ('TaskManagerApp', '0006_auto_20240120_1032'),
    ]
    
    operations = [ migrations.RemoveField(
        model_name='task',
        name='EffortsId',
        )
    ]
