# Generated by Django 4.0 on 2024-01-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0006_tasktype_company_task_tasktypeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='person',
            name='MobilePhone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='WorkPhone',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
