# Generated by Django 4.0 on 2024-01-07 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0007_remove_person_phonenumber_person_mobilephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='Position',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='TaskId',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='DepartmentName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TaskManagerApp.department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='FullName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Patronymic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='Surname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
