# Generated by Django 4.0 on 2024-01-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0007_auto_20240120_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effortsstats',
            name='EffortsId',
        ),
        migrations.RemoveField(
            model_name='effortsstats',
            name='FinishTimeThisDay',
        ),
        migrations.RemoveField(
            model_name='effortsstats',
            name='StartTimeThisDay',
        ),
        migrations.AddField(
            model_name='task',
            name='CategoryOfTaskName',
            field=models.ManyToManyField(through='TaskManagerApp.CategorySet', to='TaskManagerApp.CategoryOfTask'),
        ),
        migrations.AddField(
            model_name='task',
            name='EffortsId',
            field=models.ManyToManyField(to='TaskManagerApp.EffortsStats'),
        ),
        migrations.DeleteModel(
            name='Efforts',
        ),
    ]
