# Generated by Django 4.0 on 2024-01-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0008_remove_effortsstats_effortsid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='DateRegistration',
            field=models.DateTimeField(db_index=True, default=None),
        ),
    ]
