# Generated by Django 4.0 on 2024-01-10 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('TaskManagerApp', '0009_alter_person_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Efforts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EffortsId', models.CharField(blank=True, max_length=127, null=True)),
            ],
            options={
                'verbose_name_plural': 'Efforts',
            },
        ),
        migrations.CreateModel(
            name='EffortsStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comments', models.TextField()),
                ('TimeOfAction', models.TimeField()),
                ('DateOfAction', models.DateTimeField(default=None)),
                ('StartTimeThisDay', models.TimeField()),
                ('FinishTimeThisDay', models.TimeField()),
                ('EffortsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.efforts')),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='CompanyName',
        ),
        migrations.RemoveField(
            model_name='company',
            name='TaskId',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ActualExecutionTime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ProcentDone',
        ),
        migrations.AddField(
            model_name='company',
            name='CompanyAddress',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='CompanyFax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='CompanyFullName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='CompanyLogo',
            field=models.ImageField(blank=True, height_field=10, null=True, upload_to='', width_field=10),
        ),
        migrations.AddField(
            model_name='company',
            name='CompanyPhone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='CompanyShortName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='CompanyName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TaskManagerApp.company'),
        ),
        migrations.AddField(
            model_name='task',
            name='CompanyName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TaskManagerApp.company'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='CategoryOfTaskName',
        ),
        migrations.AddField(
            model_name='task',
            name='CategoryOfTaskName',
            field=models.ManyToManyField(to='TaskManagerApp.CategoryOfTask'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='ServiceName',
        ),
        migrations.AddField(
            model_name='task',
            name='ServiceName',
            field=models.ManyToManyField(to='TaskManagerApp.Service'),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskId',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='ExecutionTime',
        ),
        migrations.AddField(
            model_name='effortsstat',
            name='TaskId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.task'),
        ),
        migrations.AddField(
            model_name='efforts',
            name='TaskId',
            field=models.ManyToManyField(through='TaskManagerApp.EffortsStat', to='TaskManagerApp.Task'),
        ),
    ]
