# Generated by Django 4.0 on 2024-01-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0009_alter_task_dateregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=None)),
                ('isWorkday', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OfficeHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=None)),
                ('WorkdayStart', models.TimeField()),
                ('WorkdayEnd', models.TimeField()),
            ],
        ),
    ]
