# Generated by Django 4.0 on 2024-01-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0010_officecalendar_officehours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officehours',
            name='WorkdayEnd',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='officehours',
            name='WorkdayStart',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='DateOfDone',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='DateRegistration',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
