# Generated by Django 4.0 on 2024-01-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0011_alter_company_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='efforts',
            name='TaskId',
        ),
        migrations.AddField(
            model_name='task',
            name='EffortsId',
            field=models.ManyToManyField(through='TaskManagerApp.EffortsStat', to='TaskManagerApp.Efforts'),
        ),
    ]
