# Generated by Django 4.0 on 2024-01-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0012_alter_officehours_workdayend_and_more'),
    ]

    operations = [ migrations.RemoveField(
        model_name='task',
        name='EffortsId',
        )
    ]
