# Generated by Django 4.0 on 2024-01-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0013_auto_20240125_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effortsstats',
            name='TaskId',
        ),
        migrations.AlterField(
            model_name='officecalendar',
            name='Date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='officehours',
            name='Date',
            field=models.DateField(default=None),
        ),
    ]
