# Generated by Django 4.0 on 2024-01-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0014_remove_effortsstats_taskid_alter_officecalendar_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='EffortsId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TaskManagerApp.effortsstats'),
        ),
    ]
