# Generated by Django 4.0 on 2024-02-29 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0017_rename_situationname_task_situationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Comments',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='PriorityColor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ProjectName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TaskManagerApp.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ResultOfTaskName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TaskManagerApp.resultoftask'),
        ),
        migrations.AlterField(
            model_name='task',
            name='manual_selection',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='manual_sort',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
