# Generated by Django 4.0 on 2024-02-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0018_alter_task_comments_alter_task_prioritycolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='DateOfDone',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='DateRegistration',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='Description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
