# Generated by Django 4.0 on 2024-04-15 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0019_alter_task_dateofdone_alter_task_dateregistration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultoftask',
            old_name='ResultOfTaskName',
            new_name='Name',
        ),
    ]
