# Generated by Django 4.0 on 2024-04-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0020_rename_resultoftaskname_resultoftask_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='CompanyAddress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='CompanyFax',
            new_name='Fax',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='CompanyFullName',
            new_name='FullName',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='CompanyLogo',
            new_name='Logo',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='CompanyPhone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='CompanyShortName',
            new_name='ShortName',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='CompanyName',
            new_name='CompanyId',
        ),
    ]
