# Generated by Django 4.0 on 2024-05-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0021_rename_companyaddress_company_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='PersonFullName',
            new_name='PersonFullNameId',
        ),
    ]
