# Generated by Django 4.0 on 2024-05-16 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0022_rename_personfullname_task_personfullnameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='PersonFullNameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PersonFullNameIds', to='TaskManagerApp.person'),
        ),
    ]
