# Generated by Django 4.0 on 2024-05-21 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0024_rename_author_task_createdbyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceset',
            name='ServiceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_set', related_query_name='service_id_s', to='TaskManagerApp.service'),
        ),
        migrations.AlterField(
            model_name='serviceset',
            name='TaskId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_set', related_query_name='task_id_s', to='TaskManagerApp.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ServiceName',
            field=models.ManyToManyField(related_name='tasks_service_name', related_query_name='tasks_service_name', through='TaskManagerApp.ServiceSet', to='TaskManagerApp.Service'),
        ),
    ]
