# Generated by Django 4.0 on 2024-05-22 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0026_alter_task_situationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceset',
            name='ServiceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_id', related_query_name='service_id_s', to='TaskManagerApp.service'),
        ),
        migrations.AlterField(
            model_name='serviceset',
            name='TaskId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_id', related_query_name='task_id_s', to='TaskManagerApp.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ServiceName',
            field=models.ManyToManyField(through='TaskManagerApp.ServiceSet', to='TaskManagerApp.Service'),
        ),
    ]
