# Generated by Django 4.0 on 2024-05-23 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('TaskManagerApp', '0027_alter_serviceset_serviceid_alter_serviceset_taskid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='CompanyId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.company'),
        ),
        migrations.AlterField(
            model_name='task',
            name='CreatedByUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='task',
            name='EffortsId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.effortsstats'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ITTaskTypeName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.ittasktype'),
        ),
        migrations.AlterField(
            model_name='task',
            name='PersonFullNameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonFullNameIds', to='TaskManagerApp.person'),
        ),
        migrations.AlterField(
            model_name='task',
            name='Priority',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.priorityinfo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ProjectName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ResultOfTaskName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.resultoftask'),
        ),
        migrations.AlterField(
            model_name='task',
            name='SituationType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.situation'),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskTypeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.tasktype'),
        ),
        migrations.AlterField(
            model_name='task',
            name='TypeOfActionName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.typeofaction'),
        ),
    ]
