# Generated by Django 4.0 on 2024-05-23 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0028_alter_task_companyid_alter_task_createdbyuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='CompanyName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.company'),
        ),
        migrations.AlterField(
            model_name='person',
            name='DepartmentName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.department'),
        ),
    ]
