# Generated by Django 4.0 on 2024-05-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0029_alter_person_companyname_alter_person_departmentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='modified',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='DateRegistration',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
