# Generated by Django 4.0 on 2024-05-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0030_task_modified_alter_task_dateregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='DateRegistration',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
