# Generated by Django 4.0 on 2024-05-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0031_alter_task_dateregistration'),
    ]

    operations = [migrations.RemoveField(
        model_name='task',
        name='EffortsId',
        )
    ]
