# Generated by Django 4.0 on 2024-05-25 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0033_task_effortsid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='EffortsId',
        ),
    ]
