# Generated by Django 4.0 on 2024-05-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0034_remove_task_effortsid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EffortsStats',
        ),
        migrations.AlterField(
            model_name='officehours',
            name='WorkdayEnd',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='officehours',
            name='WorkdayStart',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
