# Generated by Django 4.0 on 2024-05-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0035_delete_effortsstats_alter_officehours_workdayend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTimeOfAction', models.TimeField(blank=True, default=None, null=True)),
                ('dateOfAction', models.DateTimeField(blank=True, default=None, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'TimeIntervals',
            },
        ),
    ]
