# Generated by Django 4.0 on 2024-05-25 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0036_timeinterval'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffortsStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comments', models.TextField()),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.task')),
                ('TimeInterval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.timeinterval')),
            ],
            options={
                'verbose_name_plural': 'EffortsStats',
            },
        ),
    ]
