# Generated by Django 4.0 on 2024-05-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0037_effortsstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='EffortsId',
            field=models.ManyToManyField(through='TaskManagerApp.EffortsStats', to='TaskManagerApp.TimeInterval'),
        ),
    ]
