# Generated by Django 4.0 on 2024-06-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0038_task_effortsid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='PriorityColor',
        ),
    ]
