# Generated by Django 4.0 on 2024-06-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0039_prioritycolor_remove_task_prioritycolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoryPoint', models.PositiveIntegerField(blank=True, null=True)),
                ('Volume', models.PositiveIntegerField(blank=True, null=True)),
                ('RiskAndUncertaintly', models.PositiveIntegerField(blank=True, null=True)),
                ('Complexity', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'StoryPoint',
            },
        ),
    ]
