# Generated by Django 4.0 on 2024-06-02 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0041_remove_task_tasktypeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='StoryPoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.storypoint'),
        ),
    ]
