# Generated by Django 4.0 on 2024-06-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0042_task_storypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='prioritycolor',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
