# Generated by Django 4.0 on 2024-06-03 05:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0043_prioritycolor_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prioritycolor',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
