# Generated by Django 4.0 on 2024-06-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0044_alter_prioritycolor_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorityinfo',
            name='PriorityColor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
