# Generated by Django 4.0 on 2024-06-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0045_priorityinfo_prioritycolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priorityinfo',
            name='PriorityColor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
