# Generated by Django 4.0 on 2024-06-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0046_alter_priorityinfo_prioritycolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TaskManagerApp.priorityinfo'),
        ),
    ]
