# Generated by Django 4.0 on 2024-06-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0047_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priorityinfo',
            name='PriorityColor',
        ),
        migrations.AddField(
            model_name='task',
            name='PriorityColor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
