version: '3'

services:
  web:
    build: ./TaskManager
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web_django
    ports:
      - '8000:8000'
    expose:
      - "8000"
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: 'TaskManagerDB'
      MYSQL_USER: 'siteadmin'
      MYSQL_PASSWORD: 'TaskManagerDB!#314'
      MYSQL_ROOT_PASSWORD: 'TaskManagerDB!#314'
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
