
// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    id: 'id',
    label: '#',
    pathJSON: 'id',
    optionListObjName: 'id',
    show: false,
    editable: false,
    autoFilling: false,
    type: 'input', 
    ObjectInputType: 'input',
    sample: 1425,
    align: 'center',
  },
  {
    id: 'CompanyName',
    label: 'Компания',
    pathJSON: 'CompanyId.ShortName',
    optionListObjName: 'id',
    type: 'input',
    ObjectInputType: 'input',
    show: false,
    editable: false, 
    autoFilling: false,
    sample: 1,
  },
  {
    id: 'TaskId',
    label: 'TaskId',
    pathJSON: 'TaskId', 
    optionListObjName: 'id',
    type: 'input',
    ObjectInputType: 'input',
    show: false,
    editable: false,
    addnew: false,
    autoFilling: false,
    sample: '_01439',
    align: 'center',
  },
  {
    id: 'TaskName',
    label: 'Название', 
    pathJSON: 'TaskName',
    optionListObjName: 'id',
    type: 'text',
    ObjectInputType: 'text',
    show: true,
    editable: true,
    addnew: false,
    autoFilling: false,   
    sample: '_17 Проект. Подключить Wi-Fi для Денисова Николая и Нечаева Дмитрия.',
    align: 'center',
  },

  {
    id: 'DateRegistration',
    label: 'DateRegistration',
    pathJSON: 'DateRegistration',
    optionListObjName: 'id',
    type: 'input', 
    ObjectInputType: 'input',
    show: false,
    editable: false,
    addnew: false,
    autoFilling: false,
    sample: '2023-03-29T00:00:00+03:00',
  },
  
  {
    id: 'SituationType',
    label: 'Ситуация',
    pathJSON: 'SituationType.SituationType',
    optionListObjName: 'SituationType',
    type: 'input',
    ObjectInputType: 'ListOptions',
    show: false,
    editable: true,
    addnew: true,
    autoFilling: false,
    sample: '',
  },
    

  {
    id: 'ServiceName',
    label: 'Сервис',
    pathJSON: 'ServiceName.[].ServiceName',
    optionListObjName: 'id',
    type: 'input',
    ObjectInputType: 'input',
    show: false,
    editable: true,
    addnew: true,
    autoFilling: false,
    sample: '',
  },
    

  {
    id: 'PersonFullNameId',
    label: 'ФИО заказчика',
    pathJSON: 'PersonFullNameId.PersonFullName',
    optionListObjName: 'PersonFullName',
    type: 'input',
    ObjectInputType: 'ListOptions',
    show: true,
    editable: true,
    addnew: true,
    autoFilling: false,
    sample: 'Денисов Николай Валерьевич',
    dataURL: "people/"
  },
    

  {
    id: 'ITTaskTypeName',
    label: 'ITTaskTypeName',
    pathJSON: 'ITTaskTypeName.ITTaskTypeName',
    optionListObjName: 'ITTaskTypeName',
    type: 'input',
    ObjectInputType: 'ListOptions',
    show: false,
    editable: true,
    addnew: true,
    autoFilling: false,
    sample: '',
  },
    

  {
    id: 'TypeOfActionName',
    label: 'TypeOfActionName',
    pathJSON: '',
    optionListObjName: 'id',
    type: 'input',
    ObjectInputType: 'input',
    show: false,
    editable: true,
    addnew: false,
    autoFilling: false,
    sample: '',
  },
    

  {
    id: 'Description',
    label: 'Description',
    pathJSON: '',
    optionListObjName: 'id',
    type: 'text',
    ObjectInputType: 'text',
    show: false,
    editable: true,
    addnew: true,
    autoFilling: false,
    sample: '',
  },
    

  {
    id: 'CategoryOfTaskName',
    label: 'CategoryOfTaskName',
    pathJSON: '',
    optionListObjName: 'id',
    type: 'input',
    ObjectInputType: 'input',
    show: false,
    editable: true,
    addnew: true,
    addnew: true,
    autoFilling: false,
    sample: '',
  },
    

  {
    id: 'ResultOfTaskName',
    label: 'ResultOfTaskName',
    pathJSON: '',
    optionListObjName: 'id',
    type: 'input',
    ObjectInputType: 'input',
    show: false,
    editable: true,
    addnew: false,
    autoFilling: false,
    sample: '',
  },
    

  {
    id: 'DateOfDone',
    label: 'DateOfDone',
    pathJSON: '',
    optionListObjName: 'id',
    type: 'input',
    ObjectInputType: 'input',
    show: false,
    editable: false,
    addnew: false,
    autoFilling: false,
    sample: '',
  },
    

  {
    id: 'Comments',
    label: 'Comments',
    pathJSON: '',
    optionListObjName: 'id',
    type: 'text',
    ObjectInputType: 'text',
    show: true,
    editable: true,
    addnew: true,
    autoFilling: false,
    sample: '  ',
  },
    

  {
    id: 'manual_selection',
    label: 'manual_selection',
    pathJSON: '',
    optionListObjName: 'id',
    type: 'input',
    ObjectInputType: 'input',
    show: false,
    editable: false,
    addnew: false,
    autoFilling: false,
    sample: '',
  },
    

  {
    id: 'manual_sort',
    label: 'manual_sort',
    pathJSON: '',
    optionListObjName: 'id',
    type: 'input',
    ObjectInputType: 'input',
    show: false,
    editable: false,
    addnew: false,
    autoFilling: false,
    sample: '',
  },
    

  {
    id: 'PriorityColor',
    label: 'PriorityColor',
    pathJSON: 'PriorityColor.color',
    optionListObjName: 'id',
    type: 'input',
    ObjectInputType: 'ColorList',
    show: true,
    editable: false,
    addnew: false,
    autoFilling: false,
    sample: '6',
  },
    

  {
    id: 'ProjectName',
    label: 'ProjectName',
    pathJSON: 'ProjectName.id',
    optionListObjName: 'fullTaskName',
    type: 'input',
    ObjectInputType: 'ListOptions',
    show: false,
    editable: true,
    addnew: true,
    autoFilling: false, //true
    sample: '',
  },
    

  {
    id: 'Priority',
    label: 'Priority',
    pathJSON: '',
    optionListObjName: 'id',
    type: 'input',
    ObjectInputType: 'input',
    show: false,
    editable: false,
    addnew: false,
    autoFilling: false,
    sample: '',
  },
    

  {
    id: 'Author',
    label: 'Author',
    pathJSON: '',
    optionListObjName: 'id',
    type: 'input',
    ObjectInputType: 'input',
    show: false,
    editable: false,
    addnew: false,
    autoFilling: false,
    sample: '',
  },
    

  {
    id: 'StoryPoint',
    label: 'StoryPoint',
    pathJSON: 'StoryPoint.StoryPoint',
    optionListObjName: 'StoryPoint',
    type: 'input',
    ObjectInputType: 'input',
    show: false,
    editable: true,
    addnew: false,
    autoFilling: false,
    sample: '',
  },
    

  {
    id: 'EffortsId',
    label: 'EffortsId',
    pathJSON: '',
    optionListObjName: 'id',
    type: 'input',
    ObjectInputType: 'input',
    show: false,
    editable: true,
    addnew: false,
    autoFilling: false,
    sample: '',
  },

]

